[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=/home/graditya/.config/qt6ct/colors/monokai.conf

[Fonts]
fixed="JetBrains Mono,10,-1,5,50,0,0,0,0,0"
general="JetBrains Mono,10,-1,5,50,0,0,0,0,0"
